server:
  port: 9090

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com.monarchwang: debug
  file: cherish.log
  config: classpath:logback.xml

mapper:
    mappers:
        - com.monarchwang.website.utils.system.MyMapper
    not-empty: false
    identity: MYSQL
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
debug: true