server:
  port: 9090
spring:
  datasource:
      name: dataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cherish
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select *
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: cherish
  redis:
    host: 101.200.57.175
    port: 6379
    password: monarchwang
    timeout: 3000
  jpa:
    show-sql: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com.monarchwang: debug
  file: cherish.log

mapper:
    mappers:
        - com.monarchwang.website.utils.MyMapper
    not-empty: false
    identity: MYSQL
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl